// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckLogin() {
  return window['go']['main']['App']['CheckLogin']();
}

export function ExportLogs(arg1) {
  return window['go']['main']['App']['ExportLogs'](arg1);
}

export function GetCities() {
  return window['go']['main']['App']['GetCities']();
}

export function GetDepsByUnit(arg1) {
  return window['go']['main']['App']['GetDepsByUnit'](arg1);
}

export function GetHospitalsByCity(arg1) {
  return window['go']['main']['App']['GetHospitalsByCity'](arg1);
}

export function GetMembers() {
  return window['go']['main']['App']['GetMembers']();
}

export function GetSchedule(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetSchedule'](arg1, arg2, arg3);
}

export function GetTicketDetail(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetTicketDetail'](arg1, arg2, arg3, arg4);
}

export function GetUserState() {
  return window['go']['main']['App']['GetUserState']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function LoadGrabConfig() {
  return window['go']['main']['App']['LoadGrabConfig']();
}

export function SaveGrabConfig(arg1) {
  return window['go']['main']['App']['SaveGrabConfig'](arg1);
}

export function SaveUserState(arg1) {
  return window['go']['main']['App']['SaveUserState'](arg1);
}

export function StartGrab(arg1) {
  return window['go']['main']['App']['StartGrab'](arg1);
}

export function StartQRLogin() {
  return window['go']['main']['App']['StartQRLogin']();
}

export function StopGrab() {
  return window['go']['main']['App']['StopGrab']();
}

export function StopQRLogin() {
  return window['go']['main']['App']['StopQRLogin']();
}

export function SubmitOrder(arg1) {
  return window['go']['main']['App']['SubmitOrder'](arg1);
}
